language: rust
cache: cargo

rust:
  - 1.27.0
  - stable
  - nightly

script:
  - cargo test --all --release
  - cargo test --all --all-features --release
  - ./test_aesni.sh

matrix:
  allow_failures:
    - name: rustfmt
    - name: clippy
    - rust: nightly
  fast_finish: true
  include:
    - name: "Rust: stable (thumbv7em-none-eabihf)"
      rust: stable
      install:
        - rustup target add thumbv7em-none-eabihf
      script:
        - cargo build --all --target thumbv7em-none-eabihf --release
    - name: "Rust: stable (wasm32-unknown-unknown)"
      rust: stable
      install:
        - rustup target add wasm32-unknown-unknown
      script:
        - cargo build --all --target wasm32-unknown-unknown --release
    - name: rustfmt
      rust: stable
      install:
        - rustup component add rustfmt
      script:
        - cargo fmt --all -- --check
    - name: clippy
      rust: stable
      install:
        - rustup component add clippy
      script:
        - cargo clippy --all
    - name: docs
      script:
        - cargo doc --all --no-deps

branches:
  only:
    - master
