[package]
name = "ctr"
version = "0.1.0"
authors = ["RustCrypto Developers"]
license = "MIT/Apache-2.0"
description = "CTR mode which implements stream cipher traits"
documentation = "https://docs.rs/ctr"
repository = "https://github.com/RustCrypto/stream-ciphers"
keywords = ["crypto", "stream-cipher", "trait"]
categories = ["cryptography", "no-std"]

[dependencies]
stream-cipher = { path = "../../traits/stream-cipher"}
block-cipher-trait = "0.5"

[dev-dependencies]
aes = "0.1"
