[package]
name = "salsa20"
version = "0.1.1"
authors = ["RustCrypto Developers"]
license = "MIT OR Apache-2.0"
description = "Salsa20 Stream Cipher"
repository = "https://github.com/RustCrypto/stream-ciphers"
keywords = ["crypto", "stream-cipher", "trait"]
categories = ["cryptography", "no-std"]

[dependencies]
block-cipher-trait = "0.6"
stream-cipher = "0.3"
salsa20-core = { version = "0.1", path = "../salsa20-core"}
zeroize = { version = "0.9", optional = true }

[dev-dependencies]
stream-cipher = { version = "0.3", features = ["dev"] }
block-cipher-trait = { version = "0.6", features = ["dev"] }

[badges]
travis-ci = { repository = "RustCrypto/stream-ciphers" }
